# Generated by Django 4.2.7 on 2023-11-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_or_video', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('program_preview', models.TextField()),
                ('what_you_will_learn', models.TextField()),
                ('bonus', models.TextField()),
                ('modules', models.PositiveIntegerField()),
                ('lessons', models.PositiveIntegerField()),
                ('difficulty', models.CharField(max_length=20)),
                ('duration', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
        ),
    ]
